default:
  allowAllIn: false
  allowAllOut: true
  allowAllFwd: false
  allowPing: true
  enableIPv6: false

security:
  alwaysDenyIP: ["1.1.1.1"]
  alwaysDenyASN: ["53667", "397702"]
  alwaysDenyAbuseIP: true
  alwaysDenyTor: false

ports:
  - port: 80
    allowIP: "cloudflare"

  - port: 443
    allowIP: "cloudflare"

  - port: 22
    proto: "tcp"
    allowIP: "0.0.0.0"
    allowCountry: "JP"
    denyFromAbuseIPs: true
    denyFromTorIPs: true
  
  - port: 3000
    allowIP: "local"
    allowInterface: "eth1"


router:
  configAsRouter: true
  privateNetwork: "192.168.10.0/24"
  wanInterface: "eth0"
  lanInterface: "eth1"
  forceDNS: "192.168.0.1"

api:
  abuseIPDBApiKey: "CHANGEME"

compatibility:
  # Allow masquerading on wireguard interfaces
  enableWireguardSupport: false
  wireguardInterfaces:
    - wg0
    - wg1

  enableDockerSupport: true
  dockerIpRange: "172.17.0.1/16"
