nftables:
  configFilePath: "./nftables.lance.conf"
  ipDefineFilePath: "./nftables.ipdefine.conf"

default:
  allowAllIn: false
  allowAllOut: true
  allowAllFwd: false
  allowPing: true
  enableIPv6: false
  enableLogging: true

ipset:
  - name: "TRUSTED"
    ip: ["0.0.0.0", "127.0.0.1"]

  - name: "DISLIKE"
    ip:
      - 192.168.1.100
      - 10.0.0.3


security:
  alwaysDenyIP: ["1.1.1.1"]
  alwaysDenyASN: ["53667", "397702"]
  alwaysDenyAbuseIP: true
  alwaysDenyTor: false

ports:
  - port: 80
    allowIP: "cloudflare"

  - port: 443
    allowIP: "cloudflare"

  - port: 22
    proto: "tcp"
    allowIP: "192.168.1.0/24"
    allowCountry: "jp"

  - port: 3000
    allowIP: "192.168.1.0/24"
    allowInterface: "eth1"


router:
  configAsRouter: true
  wanInterface: "eth0"
  privateNetworks: ["192.168.10.0/24", "192.168.20.0/24"]
  lanInterfaces: ["eth1", "wg0"]
  forceDNS: "192.168.0.1"

nat:
  - interface: "wg0"
    allowIP: "10.0.0.0/24"
    dstIP: "10.0.0.1"
    dstPort: "53"
    proto: "udp"
    natTo: "192.168.1.100:53"

api:
  abuseIPDBApiKey: "CHANGEME"
