# これを通常触る必要はないかも
nftables:
  configFilePath: "./nftables.lance.conf"
  ipDefineFilePath: "./nftables.ipdefine.conf"

default:
  allowAllIn: false
  allowAllOut: true
  allowAllFwd: false
  allowPing: true
  enableIPv6: false
  enableLogging: true

ipset:
  - name: "TRUSTED"
    ip: ["0.0.0.0", "127.0.0.1"]

  - name: "DISLIKE"
    ip:
      - 192.168.1.100
      - 10.0.0.3


security:
  alwaysDenyIP: ["1.1.1.1"]
  alwaysDenyASN: ["53667", "397702"]
  alwaysDenyTor: true

  disablePortScanProtection: false
  disableIpFragmentsBlock: false

  # クラウドプロテクション: Lance Networkを使用したアグレッシブな保護機能
  # 有効化してもサーバーからブロックされたIPなどの情報が送信されることはありませんが、正当なアクセスにも影響が出る可能性があります。
  # これは個人用のサーバーなどをより安全にするのに有効です。
  cloudProtection:
    # クラウドプロテクションを有効にする（自己責任で有効化してください）
    enableCloudProtection: true
    # パブリックプロキシのIPアドレスをブロックする
    blockPublicProxy: true
    # ボットネットなど攻撃に使用されたIPアドレスをブロックする
    blockAbuseIP: true
    # 防弾ホスティングのIPアドレスをブロックする
    blockBulletproofIP: true

ports:
  - port: 80
    allowIP: "cloudflare"

  - port: 443
    allowIP: "cloudflare"

  - port: 22
    proto: "tcp"
    allowIP: "$TRUSTED"
    allowCountry: "jp"

  - port: 3000
    allowIP: "192.168.1.0/24"
    allowInterface: "eth1"


# ルーター設定
router:
  # ルーター機能を設定するかどうか
  configAsRouter: true

  # WAN側のインターフェイス
  wanInterface: "eth0"

  # プライベートネットワークのCIDRとインターフェイス
  privateNetworks: ["192.168.10.0/24", "192.168.20.0/24"]
  lanInterfaces: ["eth1", "wg0"]

  # LAN内のデバイスに特定のDNSを強制する（AdGuard Home使用時などに有効）
  forceDNS: "192.168.0.1"

  # カスタムルート設定
  # LAN→WAN以外も許可したいとき（例えばVPNからLANへのアクセスを許可したい場合）などに使う
  customRoutes:
    - allowIP: "10.0.10.0/24"
      allowInterface: "wg1"
      allowDST: "192.168.10.0/24"

# NAT設定
nat:
  - interface: "wg0"
    # 許可するIP（必須: どこでもいいときは0.0.0.0/0）
    allowIP: "10.0.0.0/24"

    # 宛先IPがどこに向いている場合にNATするかを定義する（通常はこのデバイスのローカルIP、VPS環境などの場合はグローバルIP）
    dstIP: "10.0.0.1"

    # どのポートにどのプロトコルで来たらNATするかを定義する
    dstPort: "53"
    proto: "udp"

    # どこにNATするかを設定
    natTo: "192.168.1.100:53"
